/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAddRouteImport } from './routes/_authenticated/add'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDnaRouteImport } from './routes/_authenticated/dna'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedJourneyRouteImport } from './routes/_authenticated/journey'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReflectRouteImport } from './routes/_authenticated/reflect'
import { Route as AuthenticatedWeekRouteImport } from './routes/_authenticated/week'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAddRoute = AuthenticatedAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDnaRoute = AuthenticatedDnaRouteImport.update({
  id: '/dna',
  path: '/dna',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJourneyRoute = AuthenticatedJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReflectRoute = AuthenticatedReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWeekRoute = AuthenticatedWeekRouteImport.update({
  id: '/week',
  path: '/week',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add': typeof AuthenticatedAddRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reflect': typeof AuthenticatedReflectRoute
  '/week': typeof AuthenticatedWeekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/add': typeof AuthenticatedAddRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dna': typeof AuthenticatedDnaRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reflect': typeof AuthenticatedReflectRoute
  '/week': typeof AuthenticatedWeekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/add': typeof AuthenticatedAddRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dna': typeof AuthenticatedDnaRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/journey': typeof AuthenticatedJourneyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reflect': typeof AuthenticatedReflectRoute
  '/_authenticated/week': typeof AuthenticatedWeekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/add'
    | '/dashboard'
    | '/dna'
    | '/expenses'
    | '/journey'
    | '/profile'
    | '/reflect'
    | '/week'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/add'
    | '/dashboard'
    | '/dna'
    | '/expenses'
    | '/journey'
    | '/profile'
    | '/reflect'
    | '/week'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/add'
    | '/_authenticated/dashboard'
    | '/_authenticated/dna'
    | '/_authenticated/expenses'
    | '/_authenticated/journey'
    | '/_authenticated/profile'
    | '/_authenticated/reflect'
    | '/_authenticated/week'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/add': {
      id: '/_authenticated/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AuthenticatedAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dna': {
      id: '/_authenticated/dna'
      path: '/dna'
      fullPath: '/dna'
      preLoaderRoute: typeof AuthenticatedDnaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journey': {
      id: '/_authenticated/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AuthenticatedJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reflect': {
      id: '/_authenticated/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof AuthenticatedReflectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/week': {
      id: '/_authenticated/week'
      path: '/week'
      fullPath: '/week'
      preLoaderRoute: typeof AuthenticatedWeekRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddRoute: typeof AuthenticatedAddRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDnaRoute: typeof AuthenticatedDnaRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedJourneyRoute: typeof AuthenticatedJourneyRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReflectRoute: typeof AuthenticatedReflectRoute
  AuthenticatedWeekRoute: typeof AuthenticatedWeekRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddRoute: AuthenticatedAddRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDnaRoute: AuthenticatedDnaRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedJourneyRoute: AuthenticatedJourneyRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReflectRoute: AuthenticatedReflectRoute,
  AuthenticatedWeekRoute: AuthenticatedWeekRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
